version: '3'

services:
  web:
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////db/db.sqlite3
    working_dir: /web
    command: /web/entrypoint.sh
    build: ./web
    volumes:
      - ./web:/web
      - ./db:/db
      - ./sockets:/sockets
      - ./logs:/logs

  web_dev:
    restart: unless-stopped
    volumes:
      - ./web:/web
      - ./db:/db
      - ./sockets:/sockets
      - ./logs:/logs
    env_file:
      - .env
    environment:
      - GUNICORN_BIND=0.0.0.0:80
      - SQLALCHEMY_DATABASE_URI=sqlite:////db/db.sqlite3
    working_dir: /web
    ports:
      - "5000:80"
    build: ./web
    command: ./entrypoint.sh

  test:
    restart: unless-stopped
    volumes:
      - ./web:/web
      - ./db:/db
      - ./sockets:/sockets
      - ./logs:/logs
    env_file:
      - .env
    environment:
      - GUNICORN_BIND=0.0.0.0:80
      - SQLALCHEMY_DATABASE_URI=sqlite://
    working_dir: /web
    build: ./web
    command: python -m pytest
